# Generated by Django 4.2.6 on 2023-10-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='hover_image',
        ),
    ]
