# Generated by Django 4.2.6 on 2023-10-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_productcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ProductImg/')),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('product_purchase_price', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_description', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(max_length=300)),
                ('aditional_discription', models.CharField(blank=True, max_length=300, null=True)),
                ('stok_quantity', models.PositiveIntegerField()),
                ('categoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.productcategory', verbose_name='Product Cetegory')),
            ],
            options={
                'verbose_name_plural': 'Featured Products',
            },
        ),
    ]
