# Generated by Django 4.2.6 on 2023-10-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_featuredproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='BannerImg/')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Big Banner',
            },
        ),
        migrations.CreateModel(
            name='SectionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='SectionBannerImg/')),
                ('short_description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Section Banner',
            },
        ),
    ]
