# Generated by Django 4.2.6 on 2023-10-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_banner_sectionbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='SingleBannerImg/')),
                ('offer', models.CharField(max_length=200)),
            ],
        ),
    ]
