# Generated by Django 4.2.6 on 2023-10-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_singlebanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleBanner',
        ),
    ]
