# Generated by Django 4.2.6 on 2023-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_specialoffer_featured_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='LastBannerImg/')),
                ('sell_offer', models.CharField(max_length=150)),
                ('trends', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Last Banner',
            },
        ),
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='OurClientImg/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Our Client',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(max_length=100)),
                ('services_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
